services:
  - type: web
    runtime: docker
    name: pg-mcp
    plan: standard
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerCommand: uv run -m client.app
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: 1
    numInstances: 1
    region: ohio
    